export default {
  // Get list with all planets
  FETCH_PLANETS_REQUEST: 'FETCH_PLANETS_REQUEST',
  FETCH_PLANETS_SUCCESS: 'FETCH_PLANETS_SUCCESS',
  FETCH_PLANETS_ERROR: 'FETCH_PLANETS_ERROR',

  // Get planet info by id
  FETCH_PLANET_INFO_REQUEST: 'FETCH_PLANET_INFO_REQUEST',
  FETCH_PLANET_INFO_SUCCESS: 'FETCH_PLANET_INFO_SUCCESS',
  FETCH_PLANET_INFO_ERROR: 'FETCH_PLANET_INFO_ERROR',

  // Update planet
  UPDATE_PLANET_INFO_REQUEST: 'UPDATE_PLANET_INFO_REQUEST',
  UPDATE_PLANET_INFO_SUCCESS: 'UPDATE_PLANET_INFO_SUCCESS',
  UPDATE_PLANET_INFO_ERROR: 'UPDATE_PLANET_INFO_ERROR',
};
